### ISSUE TITLE
Autogestión para Dev [epic - task 2][spanish]

### ISSUE THREAD

**Issue by lexartlabs** [lexart-labs/tracking#4]
- Crear las tablas en la base de datos con la siguiente estructura
```
Payment_requests:
  id
  user_id
  status: pending | approved | rejected - Enum
  reply: varchar
  updated_at: timestamp
  created_at: timestamp
```

```
payment_request_detail:
  id
  payment_request_id
  concept: benefits | compensation | closure - Enum
  concept_description: varchar
  amount: double
```

- Crear endpoint ('/payment_requests/closure/:userid') que traiga las horas y montos registrados desde el último concept de tipo closure consumiendo las tablas "payment_requests", "payment_requests_details", "weeklyhours" y "tracks" para el usuario que haga la petición.
- Crear endpoint que registre un request_payment ('/payment_requests/create')
- Crear endpoint que traiga el historial de solicitudes de pago por usuario ('/payment_requests/:userid')
- Crear endpoint que modifique el status de una request_payment a cancelada desde el lado del desarrollador que la creó.
